// This file has been autogenerated from parsing an Objective-C header file added in Xcode.using System;
using System;
#if __UNIFIED__
using Foundation;
using UIKit;
#else
using MonoTouch.Foundation;
using MonoTouch.UIKit;
#endif

namespace ThemeSample.UI {
	public partial class MasterCelliPad : UITableViewCell {
		public MasterCelliPad (IntPtr handle) : base (handle)
		{
		}

		protected override void Dispose (bool disposing)
		{
			ReleaseDesignerOutlets ();
			base.Dispose (disposing);
		}
	}
}
