// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
#if __UNIFIED__
using Foundation;
using UIKit;
#else
using MonoTouch.Foundation;
using MonoTouch.UIKit;
#endif

namespace ThemeSample.UI {
	public partial class ModalViewController : UIImagePickerController {
		public ModalViewController (IntPtr handle) : base (handle)
		{
			if (UIImagePickerController.IsCameraDeviceAvailable (UIImagePickerControllerCameraDevice.Rear)) {
				SourceType = UIImagePickerControllerSourceType.Camera | UIImagePickerControllerSourceType.PhotoLibrary;
				MediaTypes = AvailableMediaTypes (SourceType);
				CameraCaptureMode = UIImagePickerControllerCameraCaptureMode.Video;
			}
		}
			
	}
}
