// This file has been autogenerated from parsing an Objective-C header file added in Xcode.using System;
using System;
using System.Drawing;
#if __UNIFIED__
using Foundation;
using UIKit;
#else
using MonoTouch.Foundation;
using MonoTouch.UIKit;
#endif

namespace ThemeSample.UI {
	public partial class AnotherElementsViewController : UIViewController {

		public AnotherElementsViewController (IntPtr handle) : base (handle)
		{
			Title = "More Elements";
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			Xamarin.Themes.CashflowTheme.Apply (View, Xamarin.Themes.ColorScheme.Black);

			ConfigureTextField (upperTextField);
			ConfigureTextField (lowerTextField);
			

			UIButton normalButton = new UIButton (new RectangleF(162,200,142,47));
			normalButton.SetTitle ("Normal", UIControlState.Normal);
			Xamarin.Themes.CashflowTheme.Apply (normalButton, Xamarin.Themes.ButtonOption.Normal);
			Add (normalButton);

			UIButton confirmButton = new UIButton (new RectangleF(17,200,142,47));
			confirmButton.SetTitle ("Confirm", UIControlState.Normal);
			Xamarin.Themes.CashflowTheme.Apply (confirmButton, Xamarin.Themes.ButtonOption.Confirm);
			Add (confirmButton);

			imageBgView.Image = UIImage.FromFile ("Images/iPhone/black/revisions-bg.png").CreateResizableImage (
				new UIEdgeInsets (50, 10, 200, 10));
		}

		[Obsolete ("Deprecated in iOS 6.0")]
		public override void ViewDidUnload ()
		{
			base.ViewDidUnload ();
			ReleaseDesignerOutlets ();
		}

		void ConfigureTextField (UITextField field)
		{
			field.LeftView = new UIView (new RectangleF(0, 0, 5, 31));
			field.LeftViewMode = UITextFieldViewMode.Always;
			field.ShouldReturn = TextFieldShouldReturn;
			Xamarin.Themes.CashflowTheme.Apply (field);
		}

		bool TextFieldShouldReturn (UITextField aTextField)
		{
			aTextField.ResignFirstResponder ();
			return true;
		}
	}
}
